export const SET_STUDENTS = "SET_STUDENTS";
export const SET_SUBJECTS = "SET_SUBJECTS";
export const SET_CLASSROOMS = "SET_CLASSROOMS";
export const UPDATE_CLASSROOM = "UPDATE_CLASSROOM";
export const UPDATE_STUDENT = "UPDATE_STUDENT";